server:
  port: 8080
spring:
  r2dbc:
    username: gam_user
    password: xxx@123123
    url: r2dbc:mysql://${MYSQL_HOST}:3306/gam_db?ssl=false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${REDIS_HOST}
    password: 12345678
  cloud:
    function:
      definition: consumerClient;routeRefresh
    stream:
      bindings:
        # 客户端事件
        consumerClient-in-0:
          destination: client-topic
        consumerClient-out-0:
          destination: client-topic

        # 路由刷新事件
        routeRefresh-in-0:
          destination: route-refresh
        routeRefresh-out-0:
          destination: route-refresh

    gateway:
      discovery:
        locator:
          enabled: false
