spring:
  r2dbc:
    username: gam_user
    password: xxx@123123
    url: r2dbc:mysql://${MYSQL_HOST}:3306/gam_db?ssl=false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${REDIS_HOST}
    password: 12345678
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false