spring:
  r2dbc:
    username: gam_user
    password: xxx@123123
    url: r2dbc:mysql://${host.mysql}:3306/gam_db?ssl=false
  rabbitmq:
    host: ${host.rabbitmq}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${host.redis}
  cloud:
    gateway:
      redis-route-definition-repository:
        enabled: false
  config:
    activate:
      on-profile: local
