POST {{gam-service}}/manager/client
Content-Type: application/json

{
  "uuid": 0,
  "ip": {
    "canonicalHostName": "String"
  },
  "name": "String",
  "type": "String",
  "service": "String",
  "describe": "String",
  "apis": [
    {
      "name": "",
      "path": "",
      "method": "",
      "service": "",
      "serviceAddress": "",
      "describe": ""
    }
  ]
}


###
GET http://localhost:8080/manager/client
