FROM openjdk:17-alpine

EXPOSE 8080
VOLUME /tmp

ENV RABBITMQ_HOST=localhost
ENV REDIS_HOST=localhost
ENV MYSQL_HOST=124.71.239.81

COPY ../gam-service/target/gam-service.jar /gam/gam-service.jar

ENTRYPOINT ["java","-jar","gam-service.jar"]
