FROM openjdk:17-alpine

EXPOSE 8080
VOLUME /tmp

ENV RABBITMQ_HOST=local
ENV REDIS_HOST=local
ENV MYSQL_HOST=124.71.239.81

COPY ./target/gam-service.jar /gam/gam-service.jar

ENTRYPOINT ["java","-jar","gam-service.jar"]
